web:
  image: local/phippy
  ports:
   - "31380:80"
  network: phippy

etcd:
  image: quay.io/coreos/etcd:v3.3.4
  ports:
   - "2379:2379"
  container_name: etcd
  network: phippy

networks:
  - phippy